apiVersion: v1
kind: Service
metadata:
  name: tascatyk8s-app-cluster-ip-service
  namespace: tascaty-app
spec:
  type: ClusterIP
  selector:
    component: tascatyk8s-app
  ports:
    - port: 8000
      targetPort: 8000