apiVersion: v1
kind: Service
metadata:
  name: tascatyk8s-db-cluster-ip-service
  namespace: tascaty-db
spec:
  type: ClusterIP
  selector:
    component: tascatyk8sdb
  ports:
    - port: 3306
      targetPort: 3306