apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
    name: tascatyk8s-db-pvc
    namespace: tascaty-db
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: managed-nfs-storage
    resources:
        requests:
            storage: 200Mi
